// ---------------------------------------------------------------------------
// AUTO-GENERATED by scripts/gen-tutorial.mjs -- DO NOT EDIT BY HAND.
//
// Faithful 1:1 mirror of the paw TUI tutorial content:
//   <paw>/tutorial_engine/content.py  (TRACKS + ALL_TRACKS)
//
// Regenerate:  npm run gen        Verify fresh:  npm run gen:check
// Keys are camelCased. Copy is verbatim except em/en dashes, normalized to
// ASCII "--" / "-" for house style (art is untouched).
// The render layer (lib/tutorial/render.ts) maps these to colored terminal
// output, mirroring tutorial_engine/engine.py render_content.
// ---------------------------------------------------------------------------

/** curses color-pair codes from engine.py: 1 CYAN 2 GREEN 3 YELLOW 4 MAGENTA 5 BOLD_WHITE */
export type TutorialColor = 1 | 2 | 3 | 4 | 5;

export interface TutorialPage {
  /** Page heading. */
  title: string;
  /** Section this page belongs to (always one of Track.sections). */
  section: string;
  /** Terminal body lines; "" is a blank line. */
  body: string[];
  /** Optional ASCII-art block, rendered in a <pre>. */
  art?: string[];
  /** Color for the whole art block when artRowColors is absent. */
  artColor?: TutorialColor;
  /** Per-row art colors (index-aligned with art); 0 means "use the block color". */
  artRowColors?: (TutorialColor | 0)[];
  /** Prefix -> color: a body line whose trimStart() startsWith(prefix) is colored + bold. */
  highlight?: Record<string, TutorialColor>;
  /** When true, the title types out once on first visit. */
  typewriterTitle?: boolean;
}

export interface Track {
  id: string;
  title: string;
  desc: string;
  time: string;
  icon: string;
  sections: string[];
  pages: TutorialPage[];
}
/** paw version this content was generated from (pyproject.toml). */
export const PAW_VERSION = "0.5.0";

/** All tracks, in TRACKS order. */
export const TRACKS: Track[] = [
  {
    "id": "terms",
    "title": "AI terminology",
    "desc": "Agents, models, tools, and paw's building blocks",
    "time": "~4 min",
    "icon": "🧭",
    "sections": [
      "The words",
      "Anatomy of an agent",
      "paw's pieces",
      "How it fits"
    ],
    "pages": [
      {
        "title": "Getting started with AI terms",
        "section": "The words",
        "body": [
          "",
          "  Before you build an agent, it helps",
          "  to know the words.",
          "",
          "  This track is a plain-language tour of",
          "  the terms you will hear all week:",
          "",
          "    model, prompt, context, tokens",
          "    agent, persona, tools, permissions",
          "    skills, hooks, rules, contexts",
          "",
          "  No jargon left unexplained."
        ],
        "typewriterTitle": true
      },
      {
        "title": "Model",
        "section": "The words",
        "body": [
          "",
          "  A MODEL is the AI brain: a large",
          "  language model (LLM) trained to predict",
          "  text.",
          "",
          "  Examples: claude-sonnet, claude-opus,",
          "  gpt-5.",
          "",
          "  * Bigger models: smarter, slower, pricier.",
          "  * Smaller models: faster, cheaper, fine",
          "    for simple jobs.",
          "",
          "  You pick the model that fits the task."
        ],
        "highlight": {
          "MODEL": 1,
          "*": 3
        }
      },
      {
        "title": "Prompt, context, tokens",
        "section": "The words",
        "body": [
          "",
          "  PROMPT   what you ask the model to do.",
          "",
          "  CONTEXT  everything the model can see",
          "           right now: your prompt, the",
          "           files, the conversation.",
          "",
          "  TOKENS   the chunks text is counted in,",
          "           roughly 3/4 of a word each.",
          "           Context has a token limit.",
          "",
          "  Good AI work is mostly about putting the",
          "  right things in the context."
        ],
        "highlight": {
          "PROMPT": 1,
          "CONTEXT": 1,
          "TOKENS": 1
        }
      },
      {
        "title": "Agent vs chatbot",
        "section": "The words",
        "body": [
          "",
          "  A CHATBOT answers.",
          "  An AGENT acts.",
          "",
          "  An agent is a model given a job, a set",
          "  of tools, and room to use them in a loop",
          "  until the job is done.",
          "",
          "  + It can read files, run commands, edit",
          "    code, and check its own work.",
          "  - It is only as safe as the limits you",
          "    put around it.",
          "",
          "  paw is those limits."
        ],
        "highlight": {
          "+": 2,
          "-": 3
        }
      },
      {
        "title": "Anatomy of an agent",
        "section": "Anatomy of an agent",
        "body": [
          "",
          "  Every agent is four choices:",
          "",
          "    a model, a persona, some tools,",
          "    and its permissions.",
          "",
          "  Get these right and the agent is useful",
          "  and safe. Get them wrong and it is a",
          "  loose cannon."
        ],
        "art": [
          "  ┌─────────────── AN AGENT ────────────────┐",
          "  │                                          │",
          "  │   model:       claude-sonnet (pinned)    │",
          "  │   persona:     'You are a security       │",
          "  │                 reviewer...'             │",
          "  │   tools:       Read, Grep, Glob          │",
          "  │   permissions: read-only                 │",
          "  │                                          │",
          "  └──────────────────────────────────────────┘"
        ],
        "artColor": 1
      },
      {
        "title": "Pinned to a model",
        "section": "Anatomy of an agent",
        "body": [
          "",
          "  An agent is PINNED to a specific model",
          "  in its config, so its behavior does not",
          "  drift when defaults change.",
          "",
          "    model: claude-sonnet",
          "",
          "  A reviewer might pin a strong model for",
          "  judgment; a quick formatter might pin a",
          "  small, fast one."
        ],
        "highlight": {
          "PINNED": 1,
          "model:": 2
        }
      },
      {
        "title": "Persona",
        "section": "Anatomy of an agent",
        "body": [
          "",
          "  The PERSONA is the agent's job, written",
          "  as a system prompt.",
          "",
          "    'You are a security reviewer. Find",
          "     injection, secrets, and auth flaws.",
          "     Report, do not fix.'",
          "",
          "  A sharp persona is the difference between",
          "  a vague answer and exactly what you",
          "  needed."
        ],
        "highlight": {
          "PERSONA": 1
        }
      },
      {
        "title": "Tools",
        "section": "Anatomy of an agent",
        "body": [
          "",
          "  TOOLS are what the agent can actually do.",
          "",
          "    Read    look at files",
          "    Grep    search the code",
          "    Bash    run commands",
          "    Edit    change files",
          "",
          "  Give an agent only the tools its job",
          "  needs. A reviewer gets Read and Grep,",
          "  not Edit."
        ],
        "highlight": {
          "TOOLS": 1
        }
      },
      {
        "title": "Permissions",
        "section": "Anatomy of an agent",
        "body": [
          "",
          "  PERMISSIONS are the guardrails on those",
          "  tools.",
          "",
          "  + read-only: look and report, changes",
          "    nothing.",
          "  + read + bash: run tests, cannot edit.",
          "  + full: implement and operate.",
          "",
          "  In paw, 14 of 18 agents are restricted.",
          "  Trust comes from limits, not hope."
        ],
        "highlight": {
          "PERMISSIONS": 1,
          "+": 2
        }
      },
      {
        "title": "paw's pieces",
        "section": "paw's pieces",
        "body": [
          "",
          "  paw gives your agent five kinds of",
          "  building block. Here is each one."
        ],
        "art": [
          "  ┌──────────┐  loads  ┌──────────┐",
          "  │  AGENTS  │ ──────> │  SKILLS  │",
          "  │ 18 roles │         │  domain  │",
          "  └────┬─────┘         └──────────┘",
          "       │ follow                     ",
          "       v                            ",
          "  ┌──────────┐  fire   ┌──────────┐",
          "  │  RULES   │ ──────> │  HOOKS   │",
          "  │  6 pages │         │  enforce │",
          "  └──────────┘         └──────────┘"
        ],
        "artColor": 1
      },
      {
        "title": "Agents and skills",
        "section": "paw's pieces",
        "body": [
          "",
          "  AGENTS are the workers. paw ships 18,",
          "  each with one narrow job: architect,",
          "  code-reviewer, bug-auditor, and more.",
          "",
          "  SKILLS are reusable domain knowledge an",
          "  agent loads on demand: security,",
          "  frontend, git-safety, and others.",
          "",
          "  An agent loads a skill to get expertise",
          "  without bloating every prompt."
        ],
        "highlight": {
          "AGENTS": 1,
          "SKILLS": 1
        }
      },
      {
        "title": "Hooks, rules, contexts",
        "section": "paw's pieces",
        "body": [
          "",
          "  RULES are the source of truth: short",
          "  docs like 'never rebase published work'.",
          "",
          "  HOOKS enforce rules mechanically. They",
          "  fire on real events and block. They do",
          "  not just suggest.",
          "",
          "  CONTEXTS set the mindset: building vs",
          "  reviewing vs a security audit.",
          "",
          "  Rules say it. Hooks make it stick."
        ],
        "highlight": {
          "RULES": 1,
          "HOOKS": 1,
          "CONTEXTS": 1
        }
      },
      {
        "title": "How it all fits",
        "section": "How it fits",
        "body": [
          "",
          "  Put together:",
          "",
          "    agents do the work,",
          "    load skills for expertise,",
          "    follow rules as the source of truth,",
          "    which hooks enforce as hard stops,",
          "    inside a context that sets the mindset.",
          "",
          "  That is a Personal Agent Workforce:",
          "  fast agents, real guardrails."
        ]
      },
      {
        "title": "Where to go next",
        "section": "How it fits",
        "body": [
          "",
          "  You have the vocabulary. Now use it:",
          "",
          "  + Learn paw:         what paw is, in depth",
          "  + Getting started:   install and run it",
          "  + Try this week:     build your own agent",
          "",
          "  The words are yours. Go build."
        ],
        "highlight": {
          "+": 2
        }
      }
    ]
  },
  {
    "id": "learn",
    "title": "Learn paw",
    "desc": "What paw is, the 5 components, concepts",
    "time": "~5 min",
    "icon": "📖",
    "sections": [
      "Welcome",
      "The Problem",
      "Components",
      "Agents",
      "Hooks & Rules"
    ],
    "pages": [
      {
        "title": "Welcome to paw",
        "section": "Welcome",
        "body": [
          "",
          "Personal Agent Workforce",
          "a Personal Agent Workforce",
          "",
          "Your AI agent writes code fast.",
          "paw makes sure it writes code right.",
          "",
          "This track covers what paw is",
          "and how it works."
        ],
        "art": [
          "        _______________        ",
          "       /               \\       ",
          "      |  ┌───┐ ┌───┐  |       ",
          "      |  │ ● │ │ ● │  |       ",
          "      |  └───┘ └───┘  |       ",
          "      |      ___      |       ",
          "      |     /   \\     |       ",
          "      |    | === |    |       ",
          "       \\   \\_____/   /        ",
          "        \\___________/         ",
          "         /    |    \\          ",
          "        *     *     *         "
        ],
        "artColor": 1,
        "typewriterTitle": true
      },
      {
        "title": "The Problem",
        "section": "The Problem",
        "body": [
          "",
          "  You:    \"Add a login endpoint\"",
          "",
          "  AI:     + Wrote the endpoint",
          "          + Handles POST /login",
          "          + Returns a JWT",
          "",
          "          - No rate limiting",
          "          - No brute-force protection",
          "          - Logs the password in plaintext",
          "          - JWT secret is hardcoded",
          "          - No test",
          "",
          "  The AI did what you asked.",
          "  The problem is what you DIDN'T ask."
        ],
        "highlight": {
          "+": 2,
          "-": 3
        }
      },
      {
        "title": "Two Choices",
        "section": "The Problem",
        "body": [
          "",
          "  OPTION A:",
          "  You review everything the AI writes.",
          "  You are now a full-time AI babysitter.",
          "  That doesn't scale.",
          "",
          "",
          "  OPTION B:",
          "  You teach the AI your standards,",
          "  and build a system that enforces them",
          "  BEFORE the code reaches you.",
          "",
          "",
          "  paw is Option B."
        ]
      },
      {
        "title": "How It All Fits Together",
        "section": "Components",
        "body": [
          "",
          "  5 layers, each works independently.",
          "",
          "  Contexts are background files fed to",
          "  agents -- project docs, stack info,",
          "  security posture. Not a role."
        ],
        "art": [
          "  ┌──────────┐     ┌──────────┐     ┌──────────┐  ",
          "  │  AGENTS  │────▶│  SKILLS  │     │ CONTEXTS │  ",
          "  │ 18 roles │     │  domain  │     │ bg info  │  ",
          "  └────┬─────┘     └──────────┘     └──────────┘  ",
          "       │                                  │        ",
          "       │ reference                   loaded by     ",
          "       ▼                                  │        ",
          "  ┌──────────┐                            │        ",
          "  │  RULES   │◄───────────────────────────┘        ",
          "  │ 6 pages  │                                     ",
          "  └────┬─────┘                                     ",
          "       │ enforced by                               ",
          "       ▼                                           ",
          "  ┌──────────┐                                     ",
          "  │  HOOKS   │  ◄── fire on Claude Code events     ",
          "  └──────────┘                                     "
        ],
        "artColor": 1
      },
      {
        "title": "Four Building Blocks",
        "section": "Components",
        "body": [
          "",
          "  AGENT  Give it a name, a model, a persona,",
          "         specific expertise. 'You are a",
          "         thorough code reviewer who catches",
          "         edge cases.'",
          "",
          "  SKILL  Instructions for a specific task.",
          "         'When reviewing, check for security,",
          "         test coverage, and naming.'",
          "",
          "  HOOK   A trigger that fires on an event.",
          "         'Before every commit, run the linter.",
          "         If it fails, block it.' Enforceable.",
          "",
          "  RULE   The standard an agent follows.",
          "         'All functions must have error",
          "         handling.' Rules guide; hooks",
          "         enforce mechanically."
        ],
        "art": [
          "  ┌──────────────────────────────────────────────┐",
          "  │        FOUR BUILDING BLOCKS                   │",
          "  ├──────────────────────────────────────────────┤",
          "  │                                              │",
          "  │  AGENT  =  WHO does the work                 │",
          "  │  SKILL  =  WHAT it knows how to do           │",
          "  │  HOOK   =  WHEN it runs automatically        │",
          "  │  RULE   =  WHY it matters                    │",
          "  │                                              │",
          "  │  That's the whole thing.                     │",
          "  └──────────────────────────────────────────────┘"
        ],
        "artColor": 2
      },
      {
        "title": "Portable by Design",
        "section": "Components",
        "body": [
          "",
          "  If you build agents and rules around YOUR",
          "  workflow, they work in any AI tool.",
          "",
          "  Claude, Cursor, Copilot, whatever's next.",
          "",
          "  If you get good at a company platform",
          "  and then leave -- you can't take it.",
          "",
          "  If you get good at writing agents and",
          "  rules -- that's yours forever.",
          "",
          "  paw agents are just markdown files.",
          "  No vendor lock-in. No magic."
        ],
        "art": [
          "  ┌──────────────────────────────────────────────┐",
          "  │  YOUR AGENTS + RULES = PORTABLE              │",
          "  ├──────────────────────────────────────────────┤",
          "  │                                              │",
          "  │  Claude Code    ✓  reads your .md files      │",
          "  │  Cursor         ✓  reads your .md files      │",
          "  │  Codex CLI      ✓  reads your .md files      │",
          "  │  Whatever's     ✓  they're just markdown     │",
          "  │   next                                       │",
          "  │                                              │",
          "  │  Company platforms don't travel with you.    │",
          "  │  Agents and rules you write are YOURS.       │",
          "  └──────────────────────────────────────────────┘"
        ],
        "artColor": 1
      },
      {
        "title": "The Key Distinction",
        "section": "Components",
        "body": [
          "",
          "  Agents without skills are smart but",
          "  uninformed.",
          "",
          "  Skills without agents are knowledge",
          "  with no one to use it.",
          "",
          "  Hooks without either still enforce",
          "  the rules -- that's the point."
        ],
        "art": [
          "  ┌──────────┬──────────────┬──────────────┬──────────────┐",
          "  │          │   AGENTS     │   SKILLS     │   HOOKS      │",
          "  ├──────────┼──────────────┼──────────────┼──────────────┤",
          "  │ What     │ AI actors    │ Knowledge    │ Scripts      │",
          "  │ Has AI?  │ Yes          │ No (teaches) │ No (enforces)│",
          "  │ Decides? │ Yes-judgment │ No-informs   │ No-reacts    │",
          "  │ Runs     │ On dispatch  │ When loaded  │ On events    │",
          "  │ Can fail │ Yes (retry)  │ N/A          │ Yes (blocks) │",
          "  │ Count    │ 18           │ 7            │ 4            │",
          "  │ Lives in │ agents/      │ skills/      │ hooks/       │",
          "  └──────────┴──────────────┴──────────────┴──────────────┘"
        ],
        "artColor": 3,
        "artRowColors": [
          3,
          1,
          3,
          2,
          4,
          2,
          4,
          2,
          4,
          2,
          3
        ]
      },
      {
        "title": "18 Agents, 5 Phases",
        "section": "Agents",
        "body": [
          "",
          "  Each agent owns a phase or dimension.",
          "  Each has minimum permissions for its job."
        ],
        "art": [
          "  ┌────────────────────────────────────────────┐",
          "  │          18 SPECIALIZED AGENTS              │",
          "  ├──────────────┬─────────────┬───────────────┤",
          "  │   PLAN       │  BUILD      │  REVIEW       │",
          "  ├──────────────┼─────────────┼───────────────┤",
          "  │ architect    │ builder     │ code-reviewer  │",
          "  │ planner      │ merge-      │ bug-auditor    │",
          "  │ devils-      │  resolver   │ security       │",
          "  │  advocate    │ migration-  │ perf-checker   │",
          "  │ rollback-    │  architect  │ fe-reviewer    │",
          "  │  planner     │             │ php-reviewer   │",
          "  │              │  RESPOND    │ test-runner    │",
          "  │              │ incident-   │ integration-   │",
          "  │  DOCUMENT    │  commander  │  tester        │",
          "  │ docs-writer  │             │ env-checker    │",
          "  └──────────────┴─────────────┴───────────────┘"
        ],
        "artColor": 1
      },
      {
        "title": "Trust Through Structural Limitation",
        "section": "Agents",
        "body": [
          "",
          "  The security-reviewer CANNOT modify code.",
          "  The test-runner CANNOT edit source files.",
          "  Only 4 of 18 get full access."
        ],
        "art": [
          "  ┌─────────────────────────────────────────────────┐",
          "  │           AGENT PERMISSION TIERS                 │",
          "  ├─────────────────────────────────────────────────┤",
          "  │  READ ONLY  (10)  Can look. Can't touch.        │",
          "  │  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  │",
          "  │  READ+BASH  (3)   Can run tests. Can't edit.   │",
          "  │  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  │",
          "  │  READ+WRITE (1)   Can edit docs. Can't run.    │",
          "  │  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  │",
          "  │  FULL       (4)   Full power. Isolated.        │",
          "  │  ████████████████████████████████████████████   │",
          "  ├─────────────────────────────────────────────────┤",
          "  │  14 of 18 agents have RESTRICTED permissions.   │",
          "  └─────────────────────────────────────────────────┘"
        ],
        "artColor": 4
      },
      {
        "title": "Hooks: Mechanical Enforcement",
        "section": "Hooks & Rules",
        "body": [
          "",
          "  Hooks fire on Claude Code lifecycle events.",
          "  They don't suggest. They BLOCK.",
          "  The dangerous command never executes."
        ],
        "art": [
          "  You type:  git rebase main                    ",
          "                                                ",
          "  ┌────────────────────────────────────────────┐",
          "  │  hooks/git_safety.py fires                 │",
          "  │                                            │",
          "  │  >>> BLOCKED <<<                            │",
          "  │                                            │",
          "  │  'git rebase rewrites published history.   │",
          "  │   Use git pull origin <branch> instead.'   │",
          "  │                                            │",
          "  │  The command NEVER executes.               │",
          "  └────────────────────────────────────────────┘"
        ],
        "artColor": 3
      },
      {
        "title": "Rules: Standards as Doctrine",
        "section": "Hooks & Rules",
        "body": [
          "",
          "  6 rules. Each is a markdown file.",
          "  Anyone can read them. Anyone can propose",
          "  changes. But they're enforced, not suggested.",
          "",
          "  git-doctrine       Always merge, never rebase",
          "  test-first         Tests before code, always",
          "  error-handling     No silent failures, ever",
          "  no-secrets-in-code Secrets in env vars only",
          "  branch-hygiene     Feature branch per task",
          "  security-basics    Validate input, encode output",
          "",
          "  Rule --> Agent enforces --> Hook blocks"
        ]
      },
      {
        "title": "Mechanical, Not Cultural",
        "section": "Hooks & Rules",
        "body": [
          "",
          "  Tribal knowledge gets forgotten.",
          "  Style guides get skipped.",
          "  Code review catches it... sometimes.",
          "",
          "  paw makes enforcement mechanical:",
          "",
          "  Rule  -->  Agent enforces it",
          "        -->  Hook prevents violations",
          "",
          "  The AI doesn't need to remember your",
          "  standards. The system enforces them."
        ],
        "art": [
          "  BEFORE (tribal knowledge):              ",
          "  ┌──────────────────────────────────────┐ ",
          "  │  'Hey, don't forget to write tests'  │ ",
          "  │  'We don't rebase here'              │ ",
          "  │  'Make sure you validate input'      │ ",
          "  └──────────────────────────────────────┘ ",
          "                                           ",
          "  AFTER (mechanical enforcement):          ",
          "  ┌──────────────────────────────────────┐ ",
          "  │  rules/test-first.md                 │ ",
          "  │    → test-runner gate BLOCKS          │ ",
          "  │  rules/git-doctrine.md               │ ",
          "  │    → hooks/git_safety.py BLOCKS       │ ",
          "  │  rules/security-basics.md            │ ",
          "  │    → security-reviewer REPORTS        │ ",
          "  └──────────────────────────────────────┘ "
        ],
        "artColor": 3
      }
    ]
  },
  {
    "id": "start",
    "title": "Getting started",
    "desc": "Install hooks, run agents, hands-on",
    "time": "~5 min",
    "icon": "🚀",
    "sections": [
      "Setup",
      "Try Hooks",
      "Try Agents",
      "What's Next"
    ],
    "pages": [
      {
        "title": "Install in 2 Minutes",
        "section": "Setup",
        "body": [
          "",
          "  Step 1: Clone paw (anywhere you want)",
          "",
          "    git clone https://github.com/Effulgent-Point/paw ~/paw",
          "    cd ~/paw",
          "",
          "  Step 2: Run setup",
          "",
          "    ./paw setup",
          "",
          "  That's it. Setup:",
          "    - Checks Python, git, terminal",
          "    - Installs hooks with correct paths",
          "    - Backs up your settings first",
          "    - Verifies everything works",
          "",
          "  Clone to ~/paw, ~/tools/paw, anywhere.",
          "  Setup detects the path automatically."
        ]
      },
      {
        "title": "Test the Hooks",
        "section": "Try Hooks",
        "body": [
          "",
          "  Open Claude Code and type:",
          "",
          "    > run git rebase main",
          "",
          "  It will be BLOCKED with an explanation.",
          "  The command never executes."
        ],
        "art": [
          "  You type:  git rebase main                    ",
          "                                                ",
          "  ┌────────────────────────────────────────────┐",
          "  │  hooks/git_safety.py fires                 │",
          "  │                                            │",
          "  │  >>> BLOCKED <<<                            │",
          "  │                                            │",
          "  │  'git rebase rewrites published history.   │",
          "  │   Use git pull origin <branch> instead.'   │",
          "  │                                            │",
          "  │  The command NEVER executes.               │",
          "  └────────────────────────────────────────────┘"
        ],
        "artColor": 3
      },
      {
        "title": "More Hook Tests",
        "section": "Try Hooks",
        "body": [
          "",
          "  Try these too:",
          "",
          "  > run git push --force origin main",
          "    BLOCKED -- overwrites remote history",
          "",
          "  > run git reset --hard HEAD~1",
          "    BLOCKED -- discards uncommitted work",
          "",
          "  > run git commit -m 'test'   (on main)",
          "    BLOCKED -- create a feature branch"
        ]
      },
      {
        "title": "Run a Review Agent",
        "section": "Try Agents",
        "body": [
          "",
          "  Make sure you have a diff (any changes).",
          "  Then type in Claude Code:",
          "",
          "    > Use the code-reviewer agent on the",
          "      current diff.",
          "",
          "  Look at the findings. Ask yourself:",
          "    - Did it catch anything you'd catch?",
          "    - Did it catch anything you WOULDN'T?",
          "    - Are the severity levels honest?"
        ]
      },
      {
        "title": "Stack Multiple Reviewers",
        "section": "Try Agents",
        "body": [
          "",
          "  Now run all three:",
          "",
          "    > Use the code-reviewer, bug-auditor,",
          "      and security-reviewer agents on the",
          "      current diff.",
          "",
          "  Or use the paw CLI:",
          "",
          "    $ paw check",
          "",
          "  Three independent perspectives.",
          "  Each catches different things.",
          "  No single reviewer covers all dimensions."
        ]
      },
      {
        "title": "What's Next",
        "section": "What's Next",
        "body": [
          "",
          "  TODAY:  Keep the hooks on. Run an agent.",
          "",
          "  THIS WEEK:  paw check on your next PR.",
          "",
          "  NEXT WEEK:  Try the full workflow.",
          "    architect -> planner -> devils-advocate",
          "    -> builder -> code-reviewer",
          "",
          "  Run the CLI track to learn paw commands.",
          "  Run the Practice track to try the buggy app."
        ],
        "art": [
          "           /\\          ",
          "          /  \\         ",
          "         / || \\        ",
          "        /  ||  \\       ",
          "       /   ||   \\      ",
          "      / ┌──────┐ \\    ",
          "     /  │ paw  │  \\   ",
          "    /   │  =>  │   \\  ",
          "   /    │ pipe │    \\ ",
          "  ╱     └──────┘     ╲",
          " ╱___________________╲",
          "     ╱╱╱    ╲╲╲       ",
          "    ╱╱╱      ╲╲╲      "
        ],
        "artColor": 2,
        "typewriterTitle": true
      }
    ]
  },
  {
    "id": "cli",
    "title": "The paw CLI",
    "desc": "Commands, presets, init, doctor",
    "time": "~3 min",
    "icon": "⌨",
    "sections": [
      "Overview",
      "Quality Gates",
      "Smart Tools",
      "Config & Health"
    ],
    "pages": [
      {
        "title": "The paw CLI",
        "section": "Overview",
        "body": [
          "",
          "  One command for everything.",
          "  Tab-completable. No memorizing prompts."
        ],
        "art": [
          "  ┌────────────────────────────────────────────┐",
          "  │  $ paw <command>                           │",
          "  ├────────────────────────────────────────────┤",
          "  │  setup       install hooks + check reqs    │",
          "  │  tutorial    this TUI walkthrough           │",
          "  │  doctor      diagnose your install          │",
          "  │  init        scaffold .paw.json config     │",
          "  │  check       generate quality gate prompt   │",
          "  │  gate <name> generate prompt for an agent  │",
          "  │  agents      list all 18 agents            │",
          "  │  version     show version                  │",
          "  └────────────────────────────────────────────┘"
        ],
        "artColor": 1
      },
      {
        "title": "Quality Gate Presets",
        "section": "Quality Gates",
        "body": [
          "",
          "  Three presets for different situations:",
          "",
          "  paw check --quick",
          "    code-reviewer only. Fast feedback.",
          "",
          "  paw check",
          "    code + bugs + security. The default.",
          "    Use before requesting code review.",
          "",
          "  paw check --thorough",
          "    All 8 reviewers. Before merging big",
          "    features or security-sensitive code."
        ]
      },
      {
        "title": "Single Gates & Agent List",
        "section": "Quality Gates",
        "body": [
          "",
          "  Run a single agent:",
          "",
          "    paw gate security",
          "    paw gate bugs",
          "    paw gate perf",
          "    paw gate frontend",
          "    paw gate php",
          "    paw gate tests",
          "    paw gate docs",
          "    paw gate env",
          "",
          "  List all agents:",
          "",
          "    paw agents"
        ]
      },
      {
        "title": "Smart Suggestions",
        "section": "Smart Tools",
        "body": [
          "",
          "  paw suggest",
          "    Reads your project files. Detects your",
          "    stack (Node, PHP, Python, Go, Rust).",
          "    Recommends which agents to enable.",
          "",
          "  paw next",
          "    Tracks your progress through paw.",
          "    Suggests the next thing to try based",
          "    on what you've already done.",
          "",
          "  paw cheatsheet",
          "    One-screen quick reference card.",
          "    All commands, agents, prompts, workflows.",
          "    Also available as printable PDF."
        ],
        "art": [
          "  ┌────────────────────────────────────────────┐",
          "  │  $ paw suggest                             │",
          "  ├────────────────────────────────────────────┤",
          "  │  Detected: Node.js + React                 │",
          "  │  Recommended agents:                       │",
          "  │    ✓ fe-reviewer     (React/JSX)            │",
          "  │    ✓ security        (npm audit)            │",
          "  │    ✗ php-reviewer    (not needed)           │",
          "  └────────────────────────────────────────────┘"
        ],
        "artColor": 2
      },
      {
        "title": "paw init -- Team Config",
        "section": "Config & Health",
        "body": [
          "",
          "  Scaffold a config for your project:",
          "",
          "    paw init",
          "",
          "  Creates .paw.json with:",
          "    - agents.enabled -- which agents run",
          "    - agents.disabled -- which to skip",
          "    - quality_gate.default_preset",
          "    - history settings",
          "",
          "  Check .paw.json into version control.",
          "  Your whole team shares the config."
        ]
      },
      {
        "title": "paw doctor -- Diagnose Issues",
        "section": "Config & Health",
        "body": [
          "",
          "  Something broken? Run:",
          "",
          "    paw doctor",
          "",
          "  Checks:",
          "    - Python version and curses module",
          "    - Hook files exist and are executable",
          "    - Hooks installed in settings.json",
          "    - All 18 agent files present",
          "    - Hook self-test (actually blocks)",
          "    - Test suite passes",
          "",
          "  Tells you exactly what's wrong",
          "  and how to fix it."
        ]
      }
    ]
  },
  {
    "id": "advanced",
    "title": "Advanced tactics",
    "desc": "Workflows, team config, customization",
    "time": "~4 min",
    "icon": "⚙",
    "sections": [
      "Workflows",
      "Customizing",
      "Scaling Up"
    ],
    "pages": [
      {
        "title": "The Full Workflow",
        "section": "Workflows",
        "body": [
          "",
          "  Plan -> Critique -> Build -> Review",
          "",
          "  1. Use the architect agent to design",
          "     a solution for [your task].",
          "",
          "  2. Use the planner agent to turn the",
          "     architecture into a plan.",
          "",
          "  3. Use the devils-advocate agent to",
          "     critique the plan.",
          "",
          "  4. Use the builder agent to implement.",
          "",
          "  5. Use the code-reviewer agent on",
          "     the changes.",
          "",
          "  The devil's advocate attacks the plan",
          "  BEFORE any code is written."
        ]
      },
      {
        "title": "Incident Response",
        "section": "Workflows",
        "body": [
          "",
          "  Production fire? Use the workflow:",
          "",
          "  1. Use the incident-commander agent.",
          "     Stop bleeding > root cause > prevent.",
          "",
          "  2. Use the rollback-planner agent.",
          "     Every fix needs a way back.",
          "",
          "  3. Use the environment-checker agent.",
          "     Verify the fix actually worked.",
          "",
          "  The incident-commander loads the",
          "  security context -- adversarial posture,",
          "  assume worst case."
        ]
      },
      {
        "title": "Workshop: Write Your Own Rule",
        "section": "Customizing",
        "body": [
          "",
          "  Think of one standard your team follows",
          "  that ISN'T written down anywhere.",
          "",
          "  Now write it as a rule:",
          "",
          "  Create rules/your-rule.md:",
          "",
          "  # [Rule Name]",
          "  **Statement:** One sentence.",
          "  **Why:** Why this matters.",
          "  ## Hard rules",
          "  - ...",
          "  **Enforced by:** which agent checks this?",
          "",
          "  Reference it in the agent's Rules section.",
          "  The rule is now mechanically enforced --",
          "  not tribal knowledge that gets forgotten."
        ]
      },
      {
        "title": "Adding Your Own Agent",
        "section": "Customizing",
        "body": [
          "",
          "  Create agents/your-agent.md:",
          "",
          "  ---",
          "  name: your-agent",
          "  description: What it does.",
          "  model: sonnet",
          "  tools: Read, Grep, Glob",
          "  ---",
          "",
          "  Then add:",
          "    Role, Context, Rules, Process,",
          "    Failure modes, Done when.",
          "",
          "  Most agents are read-only.",
          "  Only grant write/bash when needed."
        ]
      },
      {
        "title": "paw to a full pipeline",
        "section": "Scaling Up",
        "body": [
          "",
          "  paw                    pipeline",
          "  18 agents              46 agents",
          "  Manual invocation      16-phase pipeline",
          "  You sequence work      Orchestrator does",
          "  You run reviews        15 gates parallel",
          "  4 hooks                8 + self-healing",
          "  6 rules                21 doctrine pages",
          "",
          "  Start with paw.",
          "  Graduate to a full pipeline when you're ready."
        ],
        "art": [
          "           /\\          ",
          "          /  \\         ",
          "         / || \\        ",
          "        /  ||  \\       ",
          "       /   ||   \\      ",
          "      / ┌──────┐ \\    ",
          "     /  │ paw  │  \\   ",
          "    /   │  =>  │   \\  ",
          "   /    │ pipe │    \\ ",
          "  ╱     └──────┘     ╲",
          " ╱___________________╲",
          "     ╱╱╱    ╲╲╲       ",
          "    ╱╱╱      ╲╲╲      "
        ],
        "artColor": 2
      }
    ]
  },
  {
    "id": "practice",
    "title": "Practice with examples",
    "desc": "Run agents against a buggy app",
    "time": "~5 min",
    "icon": "🐛",
    "sections": [
      "The Buggy App",
      "Run Agents",
      "Results"
    ],
    "pages": [
      {
        "title": "Meet the Buggy App",
        "section": "The Buggy App",
        "body": [
          "",
          "  examples/buggy-app/app.py is a",
          "  deliberately broken Python app.",
          "",
          "  Your mission: run paw's review agents",
          "  and see how many issues they find.",
          "",
          "  Don't read the README spoilers yet."
        ],
        "art": [
          "  ┌────────────────────────────────────────────┐",
          "  │  examples/buggy-app/app.py                 │",
          "  ├────────────────────────────────────────────┤",
          "  │  6 security holes     (can you find them?) │",
          "  │  4 latent bugs        (race, off-by-one)   │",
          "  │  1 N+1 query          (perf)               │",
          "  │  0 tests              (oops)               │",
          "  │  0 input validation   (yikes)              │",
          "  └────────────────────────────────────────────┘"
        ],
        "artColor": 3
      },
      {
        "title": "What to Look For",
        "section": "The Buggy App",
        "body": [
          "",
          "  The app has problems in every category:",
          "",
          "  SECURITY   Hardcoded secrets, injection,",
          "             plaintext passwords in logs",
          "",
          "  BUGS       Off-by-one, race condition,",
          "             bare except that swallows errors",
          "",
          "  PERF       N+1 query in a loop",
          "",
          "  QUALITY    Zero tests, no input validation,",
          "             no error handling on DB connection",
          "",
          "  How many can the agents find?"
        ]
      },
      {
        "title": "Run the Security Reviewer",
        "section": "Run Agents",
        "body": [
          "",
          "  Start with security:",
          "",
          "    > Use the security-reviewer agent on",
          "      examples/buggy-app/",
          "",
          "  Or: paw gate security",
          "  (then point it at the buggy app)",
          "",
          "  Look for: OWASP categories, severity",
          "  levels, exploit paths.",
          "",
          "  How many of the 6 security holes",
          "  does it find?"
        ]
      },
      {
        "title": "Run the Bug Auditor",
        "section": "Run Agents",
        "body": [
          "",
          "  Now bugs:",
          "",
          "    > Use the bug-auditor agent on",
          "      examples/buggy-app/",
          "",
          "  Or: paw gate bugs",
          "",
          "  Look for: reproduction scenarios,",
          "  the checklist categories (off-by-one,",
          "  race condition, bare except, etc.)",
          "",
          "  How many of the 4 bugs does it find?"
        ]
      },
      {
        "title": "Run the Perf Checker",
        "section": "Run Agents",
        "body": [
          "",
          "  Performance:",
          "",
          "    > Use the perf-checker agent on",
          "      examples/buggy-app/",
          "",
          "  Or: paw gate perf",
          "",
          "  Look for: the N+1 query pattern.",
          "  Does it explain WHY it's a problem",
          "  at scale?",
          "",
          "  Good findings include scale impact:",
          "  \"fine at 100, breaks at 100K\""
        ]
      },
      {
        "title": "Check Your Results",
        "section": "Results",
        "body": [
          "",
          "  Open examples/buggy-app/README.md",
          "  and click the spoiler tag.",
          "",
          "  Compare what the agents found vs",
          "  the full list of issues.",
          "",
          "  Questions to consider:",
          "",
          "  - Did each agent stay in its lane?",
          "    (security didn't report perf issues?)",
          "  - Were severity levels accurate?",
          "  - Would you have caught all of these",
          "    in a manual review?",
          "",
          "  Now try: paw check --thorough"
        ]
      }
    ]
  },
  {
    "id": "hooks",
    "title": "Hooks deep dive",
    "desc": "How enforcement works, test and write hooks",
    "time": "~4 min",
    "icon": "🛡",
    "sections": [
      "Anatomy",
      "The Four Hooks",
      "Test Standalone",
      "Overrides",
      "Write Your Own"
    ],
    "pages": [
      {
        "title": "How a Hook Works",
        "section": "Anatomy",
        "body": [
          "",
          "  A hook is a script wired to a Claude Code",
          "  lifecycle event.",
          "",
          "  EVENT     When it fires (PreToolUse fires",
          "            BEFORE the agent runs a tool).",
          "  MATCHER   Which tools trigger it (Bash,",
          "            Write|Edit).",
          "  PAYLOAD   The tool call arrives as JSON",
          "            on stdin.",
          "  VERDICT   exit 0 allows. exit 2 blocks and",
          "            shows the agent your message.",
          "",
          "  No AI involved. No judgment. Just code",
          "  that runs every single time."
        ],
        "art": [
          "  ┌──────────────────────────────────────────┐",
          "  │            ANATOMY OF A HOOK              │",
          "  ├──────────────────────────────────────────┤",
          "  │  EVENT     PreToolUse / PostToolUse       │",
          "  │  MATCHER   Bash, Write|Edit, ...          │",
          "  │  INPUT     JSON payload on stdin          │",
          "  │  OUTPUT    exit 0 = allow                 │",
          "  │            exit 2 = BLOCK + message       │",
          "  └──────────────────────────────────────────┘"
        ]
      },
      {
        "title": "The Four Hooks",
        "section": "The Four Hooks",
        "body": [
          "",
          "  git_safety.py       PreToolUse : Bash",
          "    Blocks rebase, force-push, branch -D,",
          "    reset --hard, checkout .",
          "",
          "  branch_guard.py     PreToolUse : Bash",
          "    Blocks commits on main, master,",
          "    develop, trunk, release.",
          "",
          "  auto_test_detect.sh PostToolUse : Write|Edit",
          "    Warns when a source file has no",
          "    corresponding test file.",
          "",
          "  _lib.py             shared helpers",
          "    read_payload, emit, find_project_root.",
          "",
          "  install_hooks.py wires them into",
          "  ~/.claude/settings.json (via ./paw setup)."
        ]
      },
      {
        "title": "Pipe-Test Before You Wire",
        "section": "Test Standalone",
        "body": [
          "",
          "  Every hook is testable standalone --",
          "  before it touches your settings:",
          "",
          "  echo '{\"tool_input\":{\"command\":",
          "    \"git rebase main\"}}' |",
          "    python3 hooks/git_safety.py",
          "  echo exit=$?    # expect 2",
          "",
          "  Safe commands pass:",
          "",
          "  echo '{\"tool_input\":{\"command\":",
          "    \"git status\"}}' |",
          "    python3 hooks/git_safety.py",
          "  echo exit=$?    # expect 0",
          "",
          "  Then run the real test suite:",
          "    python3 -m pytest tests/ -v"
        ],
        "art": [
          "  ┌────────────────────────────────────────────┐",
          "  │  $ echo '{...\"git rebase main\"}'           │",
          "  │      | python3 hooks/git_safety.py         │",
          "  │                                            │",
          "  │  git rebase rewrites published history.    │",
          "  │  exit=2  ← BLOCKED                         │",
          "  └────────────────────────────────────────────┘"
        ]
      },
      {
        "title": "Escape Hatches",
        "section": "Overrides",
        "body": [
          "",
          "  Hooks block by default, but paw gives",
          "  you explicit, auditable overrides:",
          "",
          "  PAW_ALLOW_REBASE=1",
          "    Unblocks rebase -- meant for unpublished",
          "    local branches only.",
          "",
          "  PAW_ALLOW_FORCE_PUSH=1",
          "    Unblocks force push -- never to main.",
          "",
          "  The point isn't to make rules unbreakable.",
          "  It's to make breaking them a deliberate,",
          "  visible act instead of an accident."
        ]
      },
      {
        "title": "Write Your Own Hook",
        "section": "Write Your Own",
        "body": [
          "",
          "  1. Copy the pattern from an existing hook.",
          "     Import read_payload + emit from _lib.",
          "",
          "  2. Decide: PreToolUse (block) or",
          "     PostToolUse (observe/warn)?",
          "",
          "  3. Write the test FIRST in tests/.",
          "     Hooks are security-critical code.",
          "",
          "  4. Pipe-test it standalone.",
          "",
          "  5. Add it to ~/.claude/settings.json",
          "     with the matching event + matcher.",
          "",
          "  Ideas: block npm publish, warn on TODO",
          "  in committed code, block edits to .env."
        ]
      }
    ]
  },
  {
    "id": "recipes",
    "title": "Daily workflows",
    "desc": "Real-world recipes: PRs, incidents, refactors",
    "time": "~4 min",
    "icon": "🍳",
    "sections": [
      "Ship a PR",
      "Plan a Feature",
      "Fix an Incident",
      "Refactor Safely",
      "Team Setup"
    ],
    "pages": [
      {
        "title": "Recipe: The Pre-PR Ritual",
        "section": "Ship a PR",
        "body": [
          "",
          "  Before every PR:",
          "",
          "  1. paw check            (3 reviewers)",
          "  2. Fix what they found.",
          "  3. paw check --thorough (all 8)",
          "  4. Push and open the PR.",
          "",
          "  Cheap loop first, expensive loop once.",
          "  Reviewers on the PR see clean code --",
          "  and start trusting your diffs."
        ],
        "art": [
          "  ┌───────────────────────────────────────┐",
          "  │        THE PRE-PR RITUAL               │",
          "  ├───────────────────────────────────────┤",
          "  │  code  →  paw check  →  fix            │",
          "  │            ↑              │            │",
          "  │            └──────────────┘            │",
          "  │                                        │",
          "  │  paw check --thorough  →  push  →  PR  │",
          "  └───────────────────────────────────────┘"
        ]
      },
      {
        "title": "Recipe: Plan Before You Build",
        "section": "Plan a Feature",
        "body": [
          "",
          "  For anything bigger than a bug fix:",
          "",
          "  1. architect        design the approach",
          "  2. planner          break into steps",
          "  3. devils-advocate  attack the plan",
          "  4. builder          implement",
          "  5. paw check        review the result",
          "",
          "  In Claude Code:",
          "",
          "  > Use the architect agent to design",
          "    <feature>. Then have the planner",
          "    break it down and the devils-advocate",
          "    critique it before building.",
          "",
          "  The devils-advocate step is the one",
          "  people skip. It's also the one that",
          "  catches the expensive mistakes."
        ]
      },
      {
        "title": "Recipe: Incident Response",
        "section": "Fix an Incident",
        "body": [
          "",
          "  Production is broken. Don't improvise:",
          "",
          "  1. incident-commander  triage + comms",
          "  2. rollback-planner    safe way back",
          "  3. bug-auditor         find root cause",
          "  4. builder             minimal fix",
          "  5. test-runner         prove it",
          "",
          "  Rollback plan BEFORE the fix. If the",
          "  fix goes sideways at 2am, you want the",
          "  exit mapped while you were still calm."
        ]
      },
      {
        "title": "Recipe: Refactor Without Fear",
        "section": "Refactor Safely",
        "body": [
          "",
          "  Refactors fail when behavior changes",
          "  silently. Lock behavior down first:",
          "",
          "  1. test-runner          baseline: green?",
          "  2. migration-architect  plan the moves",
          "  3. builder              small steps,",
          "                          commit each one",
          "  4. integration-tester   seams still hold?",
          "  5. paw check            final gate",
          "",
          "  Small commits keep git bisect useful --",
          "  that's paw's git doctrine working",
          "  for you."
        ]
      },
      {
        "title": "Recipe: Set Up a Team Repo",
        "section": "Team Setup",
        "body": [
          "",
          "  Make the standards travel with the repo:",
          "",
          "  1. paw init             writes .paw.json",
          "  2. Commit .paw.json     team default gate",
          "  3. Copy rules/ into the repo and edit",
          "     them to match how YOUR team works.",
          "  4. Wire the pre-commit hook so branch",
          "     protection runs for everyone.",
          "",
          "  New teammate onboarding becomes:",
          "  clone, ./paw setup, done. The rules",
          "  are enforced before they read a wiki."
        ]
      }
    ]
  },
  {
    "id": "try",
    "title": "Try this week",
    "desc": "Build your first agent, rule, skill, hook",
    "time": "~3 min",
    "icon": "🎯",
    "sections": [
      "Start Here",
      "Build Yours"
    ],
    "pages": [
      {
        "title": "Your First Agent in 60 Seconds",
        "section": "Start Here",
        "body": [
          "",
          "  You don't need to install anything.",
          "  You don't need a framework.",
          "",
          "  Open your AI tool and paste:",
          "",
          "  \"You are [your name]. You are an expert",
          "   at [thing you're good at]. When asked",
          "   to [task], you always [your approach].",
          "   You never [thing you always catch].\"",
          "",
          "  That's your first agent.",
          "  Iterate from there."
        ]
      },
      {
        "title": "Find Your Rule",
        "section": "Start Here",
        "body": [
          "",
          "  Think about one thing you check EVERY",
          "  time you review someone's work.",
          "",
          "  Maybe it's:",
          "    - Error handling on every API call",
          "    - Tests for edge cases, not just happy path",
          "    - No magic numbers without a comment",
          "    - Database queries always parameterized",
          "",
          "  Write it down. One sentence.",
          "",
          "  That's a rule. Put it in rules/your-rule.md",
          "  and your AI enforces it every time."
        ]
      },
      {
        "title": "Find Your Skill",
        "section": "Start Here",
        "body": [
          "",
          "  Think about one repetitive task you do",
          "  the same way every time.",
          "",
          "  Maybe it's:",
          "    - How you set up a new API endpoint",
          "    - How you write a migration",
          "    - How you structure a PR description",
          "    - How you investigate a production issue",
          "",
          "  Write down the steps. That's a skill.",
          "  Put it in skills/your-skill/SKILL.md",
          "  and your agents can learn it."
        ]
      },
      {
        "title": "Find Your Hook",
        "section": "Build Yours",
        "body": [
          "",
          "  Think about one thing that should ALWAYS",
          "  happen before you ship work.",
          "",
          "    - Check for tests?",
          "    - Run the test suite?",
          "    - Verify spec intent was met?",
          "    - Follow existing architecture patterns?",
          "    - Check for secrets in code?",
          "",
          "  That's a hook. Write a script that checks",
          "  for it and blocks if it fails.",
          "",
          "  Rules can be broken. Hooks can't."
        ]
      },
      {
        "title": "The Whole Point",
        "section": "Build Yours",
        "body": [
          "",
          "  You can build a personal AI workforce",
          "  that does your repetitive work the way",
          "  YOU would do it.",
          "",
          "  And you can take it with you anywhere.",
          "",
          "  Start with one agent that does one thing",
          "  you already do. That's it.",
          "",
          "  paw gives you the structure.",
          "  You bring the standards."
        ],
        "art": [
          "  ┌──────────────────────────────────────────────┐",
          "  │  YOUR AGENTS + RULES = PORTABLE              │",
          "  ├──────────────────────────────────────────────┤",
          "  │                                              │",
          "  │  Claude Code    ✓  reads your .md files      │",
          "  │  Cursor         ✓  reads your .md files      │",
          "  │  Codex CLI      ✓  reads your .md files      │",
          "  │  Whatever's     ✓  they're just markdown     │",
          "  │   next                                       │",
          "  │                                              │",
          "  │  Company platforms don't travel with you.    │",
          "  │  Agents and rules you write are YOURS.       │",
          "  └──────────────────────────────────────────────┘"
        ],
        "artColor": 1,
        "typewriterTitle": true
      }
    ]
  },
  {
    "id": "contribute",
    "title": "Contributing to paw",
    "desc": "Fork, test, submit a PR",
    "time": "~2 min",
    "icon": "🤝",
    "sections": [
      "Getting Started",
      "What to Build",
      "Submit"
    ],
    "pages": [
      {
        "title": "Contributing to paw",
        "section": "Getting Started",
        "body": [
          "",
          "  paw is open source. Contributions welcome.",
          "",
          "  All PRs require maintainer approval.",
          "  Open an issue first for large changes.",
          "",
          "  Small fixes (typos, bug fixes, tests)",
          "  can go straight to a PR."
        ],
        "art": [
          "  ┌────────────────────────────────────────────┐",
          "  │         CONTRIBUTING TO PAW                 │",
          "  ├────────────────────────────────────────────┤",
          "  │                                            │",
          "  │  Fork  →  Branch  →  Test  →  PR           │",
          "  │                                            │",
          "  │  python3 -m pytest tests/ -v               │",
          "  │  ruff check .                              │",
          "  │  ruff format --check .                     │",
          "  │                                            │",
          "  │  All PRs require maintainer approval.      │",
          "  └────────────────────────────────────────────┘"
        ],
        "artColor": 1
      },
      {
        "title": "Dev Setup",
        "section": "Getting Started",
        "body": [
          "",
          "  Fork the repo on GitHub, then:",
          "",
          "    git clone https://github.com/YOU/paw ~/paw",
          "    cd ~/paw",
          "    ./paw setup",
          "",
          "  Requirements:",
          "    - Python 3.10+",
          "    - git",
          "    - Terminal with curses (macOS/Linux)",
          "",
          "  Verify:",
          "    python3 -m pytest tests/ -v",
          "    ruff check .",
          "    ruff format --check ."
        ]
      },
      {
        "title": "What You Can Build",
        "section": "What to Build",
        "body": [
          "",
          "  AGENTS   Follow agents/architect.md pattern.",
          "           Pick a context, rules, minimum tools.",
          "           Default to read-only permissions.",
          "",
          "  RULES    Follow rules/git-doctrine.md pattern.",
          "           Statement, why, hard rules, enforced by.",
          "",
          "  SKILLS   Create skills/your-skill/SKILL.md.",
          "           Domain knowledge for agents to load.",
          "",
          "  HOOKS    Changes to hooks/ require tests.",
          "           These are security-critical code.",
          "",
          "  TESTS    More coverage always welcome.",
          "           Edge cases in hooks especially."
        ]
      },
      {
        "title": "Before You Submit",
        "section": "Submit",
        "body": [
          "",
          "  Every PR must pass these checks:",
          "",
          "    python3 -m pytest tests/ -v",
          "    ruff check .",
          "    ruff format --check .",
          "",
          "  If ruff format fails, auto-fix:",
          "    ruff format .",
          "",
          "  PR guidelines:",
          "    - One feature or fix per PR",
          "    - Clear description of what and why",
          "    - Reference related issues",
          "    - Tests before code",
          "",
          "  See CONTRIBUTING.md for the full guide."
        ]
      }
    ]
  }
];

/** Track ids, in order. */
export const TRACK_IDS: string[] = TRACKS.map((t) => t.id);

/** Look up a track by id. */
export function getTrack(id: string): Track | undefined {
  return TRACKS.find((t) => t.id === id);
}

