// ---------------------------------------------------------------------------
// AUTO-GENERATED by scripts/gen-tutorial.mjs -- DO NOT EDIT BY HAND.
// Regenerate:  npm run gen        Verify fresh:  npm run gen:check
// ---------------------------------------------------------------------------

/** One searchable page: summary + flattened body text, nothing heavier. */
export interface SearchIndexEntry {
  trackId: string;
  trackTitle: string;
  trackIcon: string;
  pageIndex: number;
  section: string;
  title: string;
  text: string;
}

export const SEARCH_INDEX: SearchIndexEntry[] = [
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 0,
    "section": "The words",
    "title": "Getting started with AI terms",
    "text": "Before you build an agent, it helps to know the words. This track is a plain-language tour of the terms you will hear all week: model, prompt, context, tokens agent, persona, tools, permissions skills, hooks, rules, contexts No jargon left unexplained."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 1,
    "section": "The words",
    "title": "Model",
    "text": "A MODEL is the AI brain: a large language model (LLM) trained to predict text. Examples: claude-sonnet, claude-opus, gpt-5. * Bigger models: smarter, slower, pricier. * Smaller models: faster, cheaper, fine for simple jobs. You pick the model that fits the task."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 2,
    "section": "The words",
    "title": "Prompt, context, tokens",
    "text": "PROMPT what you ask the model to do. CONTEXT everything the model can see right now: your prompt, the files, the conversation. TOKENS the chunks text is counted in, roughly 3/4 of a word each. Context has a token limit. Good AI work is mostly about putting the right things in the context."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 3,
    "section": "The words",
    "title": "Agent vs chatbot",
    "text": "A CHATBOT answers. An AGENT acts. An agent is a model given a job, a set of tools, and room to use them in a loop until the job is done. + It can read files, run commands, edit code, and check its own work. - It is only as safe as the limits you put around it. paw is those limits."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 4,
    "section": "Anatomy of an agent",
    "title": "Anatomy of an agent",
    "text": "Every agent is four choices: a model, a persona, some tools, and its permissions. Get these right and the agent is useful and safe. Get them wrong and it is a loose cannon."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 5,
    "section": "Anatomy of an agent",
    "title": "Pinned to a model",
    "text": "An agent is PINNED to a specific model in its config, so its behavior does not drift when defaults change. model: claude-sonnet A reviewer might pin a strong model for judgment; a quick formatter might pin a small, fast one."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 6,
    "section": "Anatomy of an agent",
    "title": "Persona",
    "text": "The PERSONA is the agent's job, written as a system prompt. 'You are a security reviewer. Find injection, secrets, and auth flaws. Report, do not fix.' A sharp persona is the difference between a vague answer and exactly what you needed."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 7,
    "section": "Anatomy of an agent",
    "title": "Tools",
    "text": "TOOLS are what the agent can actually do. Read look at files Grep search the code Bash run commands Edit change files Give an agent only the tools its job needs. A reviewer gets Read and Grep, not Edit."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 8,
    "section": "Anatomy of an agent",
    "title": "Permissions",
    "text": "PERMISSIONS are the guardrails on those tools. + read-only: look and report, changes nothing. + read + bash: run tests, cannot edit. + full: implement and operate. In paw, 14 of 18 agents are restricted. Trust comes from limits, not hope."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 9,
    "section": "paw's pieces",
    "title": "paw's pieces",
    "text": "paw gives your agent five kinds of building block. Here is each one."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 10,
    "section": "paw's pieces",
    "title": "Agents and skills",
    "text": "AGENTS are the workers. paw ships 18, each with one narrow job: architect, code-reviewer, bug-auditor, and more. SKILLS are reusable domain knowledge an agent loads on demand: security, frontend, git-safety, and others. An agent loads a skill to get expertise without bloating every prompt."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 11,
    "section": "paw's pieces",
    "title": "Hooks, rules, contexts",
    "text": "RULES are the source of truth: short docs like 'never rebase published work'. HOOKS enforce rules mechanically. They fire on real events and block. They do not just suggest. CONTEXTS set the mindset: building vs reviewing vs a security audit. Rules say it. Hooks make it stick."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 12,
    "section": "How it fits",
    "title": "How it all fits",
    "text": "Put together: agents do the work, load skills for expertise, follow rules as the source of truth, which hooks enforce as hard stops, inside a context that sets the mindset. That is a personal agent workforce: fast agents, real guardrails."
  },
  {
    "trackId": "terms",
    "trackTitle": "AI terminology",
    "trackIcon": "🧭",
    "pageIndex": 13,
    "section": "How it fits",
    "title": "Where to go next",
    "text": "You have the vocabulary. Now use it: + Learn paw: what paw is, in depth + Getting started: install and run it + Try this week: build your own agent The words are yours. Go build."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 0,
    "section": "Welcome",
    "title": "Welcome to paw",
    "text": "Personal Agent Workflows an AI SDLC starter kit Your AI agent writes code fast. paw makes sure it writes code right. This track covers what paw is and how it works."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 1,
    "section": "The Problem",
    "title": "The Problem",
    "text": "You: \"Add a login endpoint\" AI: + Wrote the endpoint + Handles POST /login + Returns a JWT - No rate limiting - No brute-force protection - Logs the password in plaintext - JWT secret is hardcoded - No test The AI did what you asked. The problem is what you DIDN'T ask."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 2,
    "section": "The Problem",
    "title": "Two Choices",
    "text": "OPTION A: You review everything the AI writes. You are now a full-time AI babysitter. That doesn't scale. OPTION B: You teach the AI your standards, and build a system that enforces them BEFORE the code reaches you. paw is Option B."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 3,
    "section": "Components",
    "title": "How It All Fits Together",
    "text": "5 layers, each works independently. The pipeline composes them. It doesn't gate them."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 4,
    "section": "Components",
    "title": "Four Building Blocks",
    "text": "AGENT Give it a name, a model, a persona, specific expertise. 'You are a thorough code reviewer who catches edge cases.' SKILL Instructions for a specific task. 'When reviewing, check for security, test coverage, and naming.' HOOK A trigger that fires on an event. 'Before every commit, run the linter. If it fails, block it.' Enforceable. RULE The standards being suggested. 'All functions must have error handling.' Rules can be broken -- hooks can't."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 5,
    "section": "Components",
    "title": "Portable by Design",
    "text": "If you build agents and rules around YOUR workflow, they work in any AI tool. Claude, Cursor, Copilot, whatever's next. If you get good at a company platform and then leave -- you can't take it. If you get good at writing agents and rules -- that's yours forever. paw agents are just markdown files. No vendor lock-in. No magic."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 6,
    "section": "Components",
    "title": "The Key Distinction",
    "text": "Agents without skills are smart but uninformed. Skills without agents are knowledge with no one to use it. Hooks without either still enforce the rules -- that's the point."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 7,
    "section": "Agents",
    "title": "18 Agents, 5 Phases",
    "text": "Each agent owns a phase or dimension. Each has minimum permissions for its job."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 8,
    "section": "Agents",
    "title": "Trust Through Structural Limitation",
    "text": "The security-reviewer CANNOT modify code. The test-runner CANNOT edit source files. Only 4 of 18 get full access."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 9,
    "section": "Hooks & Rules",
    "title": "Hooks: Mechanical Enforcement",
    "text": "Hooks fire on Claude Code lifecycle events. They don't suggest. They BLOCK. The dangerous command never executes."
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 10,
    "section": "Hooks & Rules",
    "title": "Rules: Standards as Doctrine",
    "text": "6 rules. Each is a markdown file. Anyone can read them. Anyone can propose changes. But they're enforced, not suggested. git-doctrine Always merge, never rebase test-first Tests before code, always error-handling No silent failures, ever no-secrets-in-code Secrets in env vars only branch-hygiene Feature branch per task security-basics Validate input, encode output Rule --> Agent enforces --> Hook blocks"
  },
  {
    "trackId": "learn",
    "trackTitle": "Learn paw",
    "trackIcon": "📖",
    "pageIndex": 11,
    "section": "Hooks & Rules",
    "title": "Mechanical, Not Cultural",
    "text": "Tribal knowledge gets forgotten. Style guides get skipped. Code review catches it... sometimes. paw makes enforcement mechanical: Rule --> Agent enforces it --> Hook prevents violations The AI doesn't need to remember your standards. The system enforces them."
  },
  {
    "trackId": "start",
    "trackTitle": "Getting started",
    "trackIcon": "🚀",
    "pageIndex": 0,
    "section": "Setup",
    "title": "Install in 2 Minutes",
    "text": "Step 1: Clone paw (anywhere you want) git clone https://github.com/Effulgent-Point/paw ~/paw cd ~/paw Step 2: Run setup ./paw setup That's it. Setup: - Checks Python, git, terminal - Installs hooks with correct paths - Backs up your settings first - Verifies everything works Clone to ~/paw, ~/tools/paw, anywhere. Setup detects the path automatically."
  },
  {
    "trackId": "start",
    "trackTitle": "Getting started",
    "trackIcon": "🚀",
    "pageIndex": 1,
    "section": "Try Hooks",
    "title": "Test the Hooks",
    "text": "Open Claude Code and type: > run git rebase main It will be BLOCKED with an explanation. The command never executes."
  },
  {
    "trackId": "start",
    "trackTitle": "Getting started",
    "trackIcon": "🚀",
    "pageIndex": 2,
    "section": "Try Hooks",
    "title": "More Hook Tests",
    "text": "Try these too: > run git push --force origin main BLOCKED -- overwrites remote history > run git reset --hard HEAD~1 BLOCKED -- discards uncommitted work > run git commit -m 'test' (on main) BLOCKED -- create a feature branch"
  },
  {
    "trackId": "start",
    "trackTitle": "Getting started",
    "trackIcon": "🚀",
    "pageIndex": 3,
    "section": "Try Agents",
    "title": "Run a Review Agent",
    "text": "Make sure you have a diff (any changes). Then type in Claude Code: > Use the code-reviewer agent on the current diff. Look at the findings. Ask yourself: - Did it catch anything you'd catch? - Did it catch anything you WOULDN'T? - Are the severity levels honest?"
  },
  {
    "trackId": "start",
    "trackTitle": "Getting started",
    "trackIcon": "🚀",
    "pageIndex": 4,
    "section": "Try Agents",
    "title": "Stack Multiple Reviewers",
    "text": "Now run all three: > Use the code-reviewer, bug-auditor, and security-reviewer agents on the current diff. Or use the paw CLI: $ paw check Three independent perspectives. Each catches different things. No single reviewer covers all dimensions."
  },
  {
    "trackId": "start",
    "trackTitle": "Getting started",
    "trackIcon": "🚀",
    "pageIndex": 5,
    "section": "What's Next",
    "title": "What's Next",
    "text": "TODAY: Keep the hooks on. Run an agent. THIS WEEK: paw check on your next PR. NEXT WEEK: Try the full workflow. architect -> planner -> devils-advocate -> builder -> code-reviewer Run the CLI track to learn paw commands. Run the Practice track to try the buggy app."
  },
  {
    "trackId": "cli",
    "trackTitle": "The paw CLI",
    "trackIcon": "⌨",
    "pageIndex": 0,
    "section": "Overview",
    "title": "The paw CLI",
    "text": "One command for everything. Tab-completable. No memorizing prompts."
  },
  {
    "trackId": "cli",
    "trackTitle": "The paw CLI",
    "trackIcon": "⌨",
    "pageIndex": 1,
    "section": "Quality Gates",
    "title": "Quality Gate Presets",
    "text": "Three presets for different situations: paw check --quick code-reviewer only. Fast feedback. paw check code + bugs + security. The default. Use before requesting code review. paw check --thorough All 8 reviewers. Before merging big features or security-sensitive code."
  },
  {
    "trackId": "cli",
    "trackTitle": "The paw CLI",
    "trackIcon": "⌨",
    "pageIndex": 2,
    "section": "Quality Gates",
    "title": "Single Gates & Agent List",
    "text": "Run a single agent: paw gate security paw gate bugs paw gate perf paw gate frontend paw gate php paw gate tests paw gate docs paw gate env List all agents: paw agents"
  },
  {
    "trackId": "cli",
    "trackTitle": "The paw CLI",
    "trackIcon": "⌨",
    "pageIndex": 3,
    "section": "Smart Tools",
    "title": "Smart Suggestions",
    "text": "paw suggest Reads your project files. Detects your stack (Node, PHP, Python, Go, Rust). Recommends which agents to enable. paw next Tracks your progress through paw. Suggests the next thing to try based on what you've already done. paw cheatsheet One-screen quick reference card. All commands, agents, prompts, workflows. Also available as printable PDF."
  },
  {
    "trackId": "cli",
    "trackTitle": "The paw CLI",
    "trackIcon": "⌨",
    "pageIndex": 4,
    "section": "Config & Health",
    "title": "paw init -- Team Config",
    "text": "Scaffold a config for your project: paw init Creates .paw.json with: - agents.enabled -- which agents run - agents.disabled -- which to skip - quality_gate.default_preset - history settings Check .paw.json into version control. Your whole team shares the config."
  },
  {
    "trackId": "cli",
    "trackTitle": "The paw CLI",
    "trackIcon": "⌨",
    "pageIndex": 5,
    "section": "Config & Health",
    "title": "paw doctor -- Diagnose Issues",
    "text": "Something broken? Run: paw doctor Checks: - Python version and curses module - Hook files exist and are executable - Hooks installed in settings.json - All 18 agent files present - Hook self-test (actually blocks) - Test suite passes Tells you exactly what's wrong and how to fix it."
  },
  {
    "trackId": "advanced",
    "trackTitle": "Advanced tactics",
    "trackIcon": "⚙",
    "pageIndex": 0,
    "section": "Workflows",
    "title": "The Full Workflow",
    "text": "Plan -> Critique -> Build -> Review 1. Use the architect agent to design a solution for [your task]. 2. Use the planner agent to turn the architecture into a plan. 3. Use the devils-advocate agent to critique the plan. 4. Use the builder agent to implement. 5. Use the code-reviewer agent on the changes. The devil's advocate attacks the plan BEFORE any code is written."
  },
  {
    "trackId": "advanced",
    "trackTitle": "Advanced tactics",
    "trackIcon": "⚙",
    "pageIndex": 1,
    "section": "Workflows",
    "title": "Incident Response",
    "text": "Production fire? Use the workflow: 1. Use the incident-commander agent. Stop bleeding > root cause > prevent. 2. Use the rollback-planner agent. Every fix needs a way back. 3. Use the environment-checker agent. Verify the fix actually worked. The incident-commander loads the security context -- adversarial mindset, assume worst case."
  },
  {
    "trackId": "advanced",
    "trackTitle": "Advanced tactics",
    "trackIcon": "⚙",
    "pageIndex": 2,
    "section": "Customizing",
    "title": "Workshop: Write Your Own Rule",
    "text": "Think of one standard your team follows that ISN'T written down anywhere. Now write it as a rule: Create rules/your-rule.md: # [Rule Name] **Statement:** One sentence. **Why:** Why this matters. ## Hard rules - ... **Enforced by:** which agent checks this? Reference it in the agent's Rules section. The rule is now mechanically enforced -- not tribal knowledge that gets forgotten."
  },
  {
    "trackId": "advanced",
    "trackTitle": "Advanced tactics",
    "trackIcon": "⚙",
    "pageIndex": 3,
    "section": "Customizing",
    "title": "Adding Your Own Agent",
    "text": "Create agents/your-agent.md: --- name: your-agent description: What it does. model: sonnet tools: Read, Grep, Glob --- Then add: Role, Context, Rules, Process, Failure modes, Done when. Most agents are read-only. Only grant write/bash when needed."
  },
  {
    "trackId": "advanced",
    "trackTitle": "Advanced tactics",
    "trackIcon": "⚙",
    "pageIndex": 4,
    "section": "Scaling Up",
    "title": "paw to forge",
    "text": "paw forge 18 agents 46 agents Manual invocation 16-phase pipeline You sequence work Orchestrator does You run reviews 15 gates parallel 4 hooks 8 + self-healing 6 rules 21 doctrine pages Start with paw. Graduate to forge when you're ready."
  },
  {
    "trackId": "practice",
    "trackTitle": "Practice with examples",
    "trackIcon": "🐛",
    "pageIndex": 0,
    "section": "The Buggy App",
    "title": "Meet the Buggy App",
    "text": "examples/buggy-app/app.py is a deliberately broken Python app. Your mission: run paw's review agents and see how many issues they find. Don't read the README spoilers yet."
  },
  {
    "trackId": "practice",
    "trackTitle": "Practice with examples",
    "trackIcon": "🐛",
    "pageIndex": 1,
    "section": "The Buggy App",
    "title": "What to Look For",
    "text": "The app has problems in every category: SECURITY Hardcoded secrets, injection, plaintext passwords in logs BUGS Off-by-one, race condition, bare except that swallows errors PERF N+1 query in a loop QUALITY Zero tests, no input validation, no error handling on DB connection How many can the agents find?"
  },
  {
    "trackId": "practice",
    "trackTitle": "Practice with examples",
    "trackIcon": "🐛",
    "pageIndex": 2,
    "section": "Run Agents",
    "title": "Run the Security Reviewer",
    "text": "Start with security: > Use the security-reviewer agent on examples/buggy-app/ Or: paw gate security (then point it at the buggy app) Look for: OWASP categories, severity levels, exploit paths. How many of the 6 security holes does it find?"
  },
  {
    "trackId": "practice",
    "trackTitle": "Practice with examples",
    "trackIcon": "🐛",
    "pageIndex": 3,
    "section": "Run Agents",
    "title": "Run the Bug Auditor",
    "text": "Now bugs: > Use the bug-auditor agent on examples/buggy-app/ Or: paw gate bugs Look for: reproduction scenarios, the checklist categories (off-by-one, race condition, bare except, etc.) How many of the 4 bugs does it find?"
  },
  {
    "trackId": "practice",
    "trackTitle": "Practice with examples",
    "trackIcon": "🐛",
    "pageIndex": 4,
    "section": "Run Agents",
    "title": "Run the Perf Checker",
    "text": "Performance: > Use the perf-checker agent on examples/buggy-app/ Or: paw gate perf Look for: the N+1 query pattern. Does it explain WHY it's a problem at scale? Good findings include scale impact: \"fine at 100, breaks at 100K\""
  },
  {
    "trackId": "practice",
    "trackTitle": "Practice with examples",
    "trackIcon": "🐛",
    "pageIndex": 5,
    "section": "Results",
    "title": "Check Your Results",
    "text": "Open examples/buggy-app/README.md and click the spoiler tag. Compare what the agents found vs the full list of issues. Questions to consider: - Did each agent stay in its lane? (security didn't report perf issues?) - Were severity levels accurate? - Would you have caught all of these in a manual review? Now try: paw check --thorough"
  },
  {
    "trackId": "hooks",
    "trackTitle": "Hooks deep dive",
    "trackIcon": "🛡",
    "pageIndex": 0,
    "section": "Anatomy",
    "title": "How a Hook Works",
    "text": "A hook is a script wired to a Claude Code lifecycle event. EVENT When it fires (PreToolUse fires BEFORE the agent runs a tool). MATCHER Which tools trigger it (Bash, Write|Edit). PAYLOAD The tool call arrives as JSON on stdin. VERDICT exit 0 allows. exit 2 blocks and shows the agent your message. No AI involved. No judgment. Just code that runs every single time."
  },
  {
    "trackId": "hooks",
    "trackTitle": "Hooks deep dive",
    "trackIcon": "🛡",
    "pageIndex": 1,
    "section": "The Four Hooks",
    "title": "The Four Hooks",
    "text": "git_safety.py PreToolUse : Bash Blocks rebase, force-push, branch -D, reset --hard, checkout . branch_guard.py PreToolUse : Bash Blocks commits on main, master, develop, trunk, release. auto_test_detect.sh PostToolUse : Write|Edit Warns when a source file has no corresponding test file. _lib.py shared helpers read_payload, emit, find_project_root. install_hooks.py wires them into ~/.claude/settings.json (via ./paw setup)."
  },
  {
    "trackId": "hooks",
    "trackTitle": "Hooks deep dive",
    "trackIcon": "🛡",
    "pageIndex": 2,
    "section": "Test Standalone",
    "title": "Pipe-Test Before You Wire",
    "text": "Every hook is testable standalone -- before it touches your settings: echo '{\"tool_input\":{\"command\": \"git rebase main\"}}' | python3 hooks/git_safety.py echo exit=$? # expect 2 Safe commands pass: echo '{\"tool_input\":{\"command\": \"git status\"}}' | python3 hooks/git_safety.py echo exit=$? # expect 0 Then run the real test suite: python3 -m pytest tests/ -v"
  },
  {
    "trackId": "hooks",
    "trackTitle": "Hooks deep dive",
    "trackIcon": "🛡",
    "pageIndex": 3,
    "section": "Overrides",
    "title": "Escape Hatches",
    "text": "Hooks block by default, but paw gives you explicit, auditable overrides: PAW_ALLOW_REBASE=1 Unblocks rebase -- meant for unpublished local branches only. PAW_ALLOW_FORCE_PUSH=1 Unblocks force push -- never to main. The point isn't to make rules unbreakable. It's to make breaking them a deliberate, visible act instead of an accident."
  },
  {
    "trackId": "hooks",
    "trackTitle": "Hooks deep dive",
    "trackIcon": "🛡",
    "pageIndex": 4,
    "section": "Write Your Own",
    "title": "Write Your Own Hook",
    "text": "1. Copy the pattern from an existing hook. Import read_payload + emit from _lib. 2. Decide: PreToolUse (block) or PostToolUse (observe/warn)? 3. Write the test FIRST in tests/. Hooks are security-critical code. 4. Pipe-test it standalone. 5. Add it to ~/.claude/settings.json with the matching event + matcher. Ideas: block npm publish, warn on TODO in committed code, block edits to .env."
  },
  {
    "trackId": "recipes",
    "trackTitle": "Daily workflows",
    "trackIcon": "🍳",
    "pageIndex": 0,
    "section": "Ship a PR",
    "title": "Recipe: The Pre-PR Ritual",
    "text": "Before every PR: 1. paw check (3 reviewers) 2. Fix what they found. 3. paw check --thorough (all 8) 4. Push and open the PR. Cheap loop first, expensive loop once. Reviewers on the PR see clean code -- and start trusting your diffs."
  },
  {
    "trackId": "recipes",
    "trackTitle": "Daily workflows",
    "trackIcon": "🍳",
    "pageIndex": 1,
    "section": "Plan a Feature",
    "title": "Recipe: Plan Before You Build",
    "text": "For anything bigger than a bug fix: 1. architect design the approach 2. planner break into steps 3. devils-advocate attack the plan 4. builder implement 5. paw check review the result In Claude Code: > Use the architect agent to design <feature>. Then have the planner break it down and the devils-advocate critique it before building. The devils-advocate step is the one people skip. It's also the one that catches the expensive mistakes."
  },
  {
    "trackId": "recipes",
    "trackTitle": "Daily workflows",
    "trackIcon": "🍳",
    "pageIndex": 2,
    "section": "Fix an Incident",
    "title": "Recipe: Incident Response",
    "text": "Production is broken. Don't improvise: 1. incident-commander triage + comms 2. rollback-planner safe way back 3. bug-auditor find root cause 4. builder minimal fix 5. test-runner prove it Rollback plan BEFORE the fix. If the fix goes sideways at 2am, you want the exit mapped while you were still calm."
  },
  {
    "trackId": "recipes",
    "trackTitle": "Daily workflows",
    "trackIcon": "🍳",
    "pageIndex": 3,
    "section": "Refactor Safely",
    "title": "Recipe: Refactor Without Fear",
    "text": "Refactors fail when behavior changes silently. Lock behavior down first: 1. test-runner baseline: green? 2. migration-architect plan the moves 3. builder small steps, commit each one 4. integration-tester seams still hold? 5. paw check final gate Small commits keep git bisect useful -- that's paw's git doctrine working for you."
  },
  {
    "trackId": "recipes",
    "trackTitle": "Daily workflows",
    "trackIcon": "🍳",
    "pageIndex": 4,
    "section": "Team Setup",
    "title": "Recipe: Set Up a Team Repo",
    "text": "Make the standards travel with the repo: 1. paw init writes .paw.json 2. Commit .paw.json team default gate 3. Copy rules/ into the repo and edit them to match how YOUR team works. 4. Wire the pre-commit hook so branch protection runs for everyone. New teammate onboarding becomes: clone, ./paw setup, done. The rules are enforced before they read a wiki."
  },
  {
    "trackId": "try",
    "trackTitle": "Try this week",
    "trackIcon": "🎯",
    "pageIndex": 0,
    "section": "Start Here",
    "title": "Your First Agent in 60 Seconds",
    "text": "You don't need to install anything. You don't need a framework. Open your AI tool and paste: \"You are [your name]. You are an expert at [thing you're good at]. When asked to [task], you always [your approach]. You never [thing you always catch].\" That's your first agent. Iterate from there."
  },
  {
    "trackId": "try",
    "trackTitle": "Try this week",
    "trackIcon": "🎯",
    "pageIndex": 1,
    "section": "Start Here",
    "title": "Find Your Rule",
    "text": "Think about one thing you check EVERY time you review someone's work. Maybe it's: - Error handling on every API call - Tests for edge cases, not just happy path - No magic numbers without a comment - Database queries always parameterized Write it down. One sentence. That's a rule. Put it in rules/your-rule.md and your AI enforces it every time."
  },
  {
    "trackId": "try",
    "trackTitle": "Try this week",
    "trackIcon": "🎯",
    "pageIndex": 2,
    "section": "Start Here",
    "title": "Find Your Skill",
    "text": "Think about one repetitive task you do the same way every time. Maybe it's: - How you set up a new API endpoint - How you write a migration - How you structure a PR description - How you investigate a production issue Write down the steps. That's a skill. Put it in skills/your-skill/SKILL.md and your agents can learn it."
  },
  {
    "trackId": "try",
    "trackTitle": "Try this week",
    "trackIcon": "🎯",
    "pageIndex": 3,
    "section": "Build Yours",
    "title": "Find Your Hook",
    "text": "Think about one thing that should ALWAYS happen before you ship work. - Check for tests? - Run the test suite? - Verify spec intent was met? - Follow existing architecture patterns? - Check for secrets in code? That's a hook. Write a script that checks for it and blocks if it fails. Rules can be broken. Hooks can't."
  },
  {
    "trackId": "try",
    "trackTitle": "Try this week",
    "trackIcon": "🎯",
    "pageIndex": 4,
    "section": "Build Yours",
    "title": "The Whole Point",
    "text": "You can build a personal AI workforce that does your repetitive work the way YOU would do it. And you can take it with you anywhere. Start with one agent that does one thing you already do. That's it. paw gives you the structure. You bring the standards."
  },
  {
    "trackId": "contribute",
    "trackTitle": "Contributing to paw",
    "trackIcon": "🤝",
    "pageIndex": 0,
    "section": "Getting Started",
    "title": "Contributing to paw",
    "text": "paw is open source. Contributions welcome. All PRs require maintainer approval. Open an issue first for large changes. Small fixes (typos, bug fixes, tests) can go straight to a PR."
  },
  {
    "trackId": "contribute",
    "trackTitle": "Contributing to paw",
    "trackIcon": "🤝",
    "pageIndex": 1,
    "section": "Getting Started",
    "title": "Dev Setup",
    "text": "Fork the repo on GitHub, then: git clone https://github.com/YOU/paw ~/paw cd ~/paw ./paw setup Requirements: - Python 3.10+ - git - Terminal with curses (macOS/Linux) Verify: python3 -m pytest tests/ -v ruff check . ruff format --check ."
  },
  {
    "trackId": "contribute",
    "trackTitle": "Contributing to paw",
    "trackIcon": "🤝",
    "pageIndex": 2,
    "section": "What to Build",
    "title": "What You Can Build",
    "text": "AGENTS Follow agents/architect.md pattern. Pick a context, rules, minimum tools. Default to read-only permissions. RULES Follow rules/git-doctrine.md pattern. Statement, why, hard rules, enforced by. SKILLS Create skills/your-skill/SKILL.md. Domain knowledge for agents to load. HOOKS Changes to hooks/ require tests. These are security-critical code. TESTS More coverage always welcome. Edge cases in hooks especially."
  },
  {
    "trackId": "contribute",
    "trackTitle": "Contributing to paw",
    "trackIcon": "🤝",
    "pageIndex": 3,
    "section": "Submit",
    "title": "Before You Submit",
    "text": "Every PR must pass these checks: python3 -m pytest tests/ -v ruff check . ruff format --check . If ruff format fails, auto-fix: ruff format . PR guidelines: - One feature or fix per PR - Clear description of what and why - Reference related issues - Tests before code See CONTRIBUTING.md for the full guide."
  }
];
