// ---------------------------------------------------------------------------
// AUTO-GENERATED by scripts/gen-tutorial.mjs -- DO NOT EDIT BY HAND.
// Regenerate:  npm run gen        Verify fresh:  npm run gen:check
// ---------------------------------------------------------------------------

/** Lightweight track metadata for the tutorial landing grid (no page bodies). */
export interface TrackSummary {
  id: string;
  title: string;
  desc: string;
  time: string;
  icon: string;
  pageCount: number;
}

export const TRACK_SUMMARIES: TrackSummary[] = [
  {
    "id": "terms",
    "title": "AI terminology",
    "desc": "Agents, models, tools, and paw's building blocks",
    "time": "~4 min",
    "icon": "🧭",
    "pageCount": 14
  },
  {
    "id": "learn",
    "title": "Learn paw",
    "desc": "What paw is, the 5 components, concepts",
    "time": "~5 min",
    "icon": "📖",
    "pageCount": 12
  },
  {
    "id": "start",
    "title": "Getting started",
    "desc": "Install hooks, run agents, hands-on",
    "time": "~5 min",
    "icon": "🚀",
    "pageCount": 6
  },
  {
    "id": "cli",
    "title": "The paw CLI",
    "desc": "Commands, presets, init, doctor",
    "time": "~3 min",
    "icon": "⌨",
    "pageCount": 6
  },
  {
    "id": "advanced",
    "title": "Advanced tactics",
    "desc": "Workflows, team config, customization",
    "time": "~4 min",
    "icon": "⚙",
    "pageCount": 5
  },
  {
    "id": "practice",
    "title": "Practice with examples",
    "desc": "Run agents against a buggy app",
    "time": "~5 min",
    "icon": "🐛",
    "pageCount": 6
  },
  {
    "id": "hooks",
    "title": "Hooks deep dive",
    "desc": "How enforcement works, test and write hooks",
    "time": "~4 min",
    "icon": "🛡",
    "pageCount": 5
  },
  {
    "id": "recipes",
    "title": "Daily workflows",
    "desc": "Real-world recipes: PRs, incidents, refactors",
    "time": "~4 min",
    "icon": "🍳",
    "pageCount": 5
  },
  {
    "id": "try",
    "title": "Try this week",
    "desc": "Build your first agent, rule, skill, hook",
    "time": "~3 min",
    "icon": "🎯",
    "pageCount": 5
  },
  {
    "id": "contribute",
    "title": "Contributing to paw",
    "desc": "Fork, test, submit a PR",
    "time": "~2 min",
    "icon": "🤝",
    "pageCount": 4
  }
];
